stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./ManaBurnServer/ManaBurnServer/Dockerfile
      buildContext: ./ManaBurnServer
      tag: atriarch-manaburn-server:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./ManaBurnServer/ManaBurnServer/deployment.yaml
    when:
      branch:
        include:
        - master
timeout: 60
branch: {}
notification:
  recipients:
  - recipient: pipelineNotifications@mail.atriarch.systems
    notifier: c-56lvs:n-45qs9
  condition:
  - Failed
