stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./ManaBurnServer/ManaBurnServer/Dockerfile
      buildContext: ./ManaBurnServer
      tag: atriarch-manaburn-server:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./ManaBurnServer/ManaBurnServer/deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: dan@mail.atriarch.systems
    notifier: c-xc9r9:n-g2gcc
  condition:
  - Failed
