apiVersion: v1
kind: ConfigMap
metadata:
  name: manaburn-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manaburn-server-deployment
  namespace: manaburn # The namespace the app will use
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manaburn
  template:
    metadata:
      labels:
        app: manaburn
    spec:
      containers:
      - name: manaburn-server-container
        image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE}
        volumeMounts:
        - name: appconfig-volume
          mountPath: /app/config
      volumes:
      - name: appconfig-volume
        configMap:
          name: manaburn-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
      imagePullSecrets:
      - name: pipeline-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: manaburn-server-service
  namespace: manaburn # The namespace the app will use
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: manaburn
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: manaburn-server-ingress
  namespace: manaburn # The namespace the app will use  
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: manaburn.drinkpoint.me
    http:
      paths:
      - path: /
        backend:
          serviceName: manaburn-server-service
          servicePort: http
