apiVersion: v1
kind: ConfigMap
metadata:
  name: manaburn-config
  namespace: manaburn # The namespace the app will use
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "System": "Information",
          "Microsoft": "Information"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manaburn-server-deployment
  namespace: manaburn # The namespace the app will use
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manaburn
  template:
    metadata:
      labels:
        app: manaburn
    spec:
      containers:
      - name: manaburn-server-container
        image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE}
        volumeMounts:
        - name: appconfig-volume
          mountPath: /app/config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Manaburn_Atriarch_ElasticSearch
          valueFrom:
            secretKeyRef:
              name: atriarch-elasticsearch-config
              key: url_internal
        - name: Manaburn_Atriarch_AuthUrl
          valueFrom:
            secretKeyRef:
              name: manaburn-client-config
              key: authorityUrl
        - name: Manaburn_Atriarch_Scope
          valueFrom:
            secretKeyRef:
              name: manaburn-client-config
              key: scope
        - name: Manaburn_Atriarch_ScopeSecret
          valueFrom:
            secretKeyRef:
              name: manaburn-client-config
              key: scopeSecret
        - name: Manaburn_Atriarch_RedisConnection
          valueFrom:
            secretKeyRef:
              name: atriarch-redis-config
              key: connectionString
        - name: Manaburn_Atriarch_PsqlConnection
          valueFrom:
            secretKeyRef:
              name: manaburn-psql-config
              key: connectionString
      volumes:
      - name: appconfig-volume
        configMap:
          name: manaburn-config
      imagePullSecrets:
      - name: pipeline-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: manaburn-server-service
  namespace: manaburn # The namespace the app will use
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: manaburn
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: manaburn-server-ingress
  namespace: manaburn # The namespace the app will use  
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: manaburn.drinkpoint.me
    http:
      paths:
      - path: /
        backend:
          serviceName: manaburn-server-service
          servicePort: http
